---
# tasks file for octoprint webcam

- name: Install mjpg-streamer dependencies.
  package:
    name: "{{ mjpg_streamer_dependencies }}"
    state: present

- name: Add webcam user to video group.
  user:
    name: "{{ webcam_user }}"
    groups: video
    system: true
    append: true

- name: Clone mjpg-streamer repo.
  git:
    repo: "{{ webcam_repo }}"
    dest: "{{ install_dir }}/mjpg-streamer"
    version: master
  register: mjpg_streamer

- name: Build mjpg-streamer from source.
  block:
    - name: Stop mjpg_streamer service if exists
      service:
        name: mjpg_streamer
        state: stopped
      failed_when: false

    - name: Build mjpg-streamer from source.
      make:
        chdir: "{{ install_dir }}/mjpg-streamer/mjpg-streamer-experimental"
        target: all
      notify: restart mjpg-streamer

  when: mjpg_streamer.changed

- name: Install systemd service template.
  template:
    src: mjpg_streamer.service.j2
    dest: /etc/systemd/system/mjpg_streamer.service
    owner: "{{ webcam_user }}"
  notify: reload systemd

- meta: flush_handlers

- name: Enable and start webcam streaming service.
  service:
    name: mjpg_streamer
    enabled: true
    state: started
