---
# handlers file for octoprint

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart octoprint
  service:
    name: octoprint
    state: restarted

- name: restart mjpg-streamer
  service:
    name: mjpg_streamer
    state: restarted
